services:
  php:
    image: php:8.4-fpm
    build: .
    container_name: php
    volumes:
      - ./:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      - SYMFONY_ENV=dev
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
  
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      - MAILPIT_RELAY=127.0.0.1:25

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "8081:80"
    depends_on:
      - mariadb

volumes:
  db_data:
